import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Content from '~/components/client/about/content'
import Heading from '~/components/client/about/heading'
import DonationBanner from '~/components/client/common/donation-banner'
import ClientLayout from '~/layouts/Client'

const Home = () => {
  return (
    <ClientLayout>
      <Head>
        <title>Acerca - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxW="5xl" margin="auto">
        <Heading />
        <Content />
        <DonationBanner />
      </Box>
    </ClientLayout>
  )
}

export default Home
