import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import DonationBanner from '~/components/client/common/donation-banner'
import DonationForm from '~/components/client/donate/donation-form'
import Heading from '~/components/client/donate/heading'
import LatestDonators from '~/components/client/donate/latest-donators'
import ClientLayout from '~/layouts/Client'

const Donate = () => {
  return (
    <ClientLayout>
      <Head>
        <title>Donaciones - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxW="7xl" margin="auto">
        <Heading />
        <LatestDonators />
        <DonationForm />
        <DonationBanner />
      </Box>
    </ClientLayout>
  )
}

export default Donate
