import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import { DonateProvider } from '~/components/client/donate/donate-context.provider'
import DonationFormHeading from '~/components/client/donate/donation-form/Heading'
import Heading from '~/components/client/donate/heading'
import LatestDonators from '~/components/client/donate/latest-donators'
import ClientLayout from '~/layouts/Client'

const Donate = () => {
  return (
    <ClientLayout>
      <Head>
        <title>Donaciones - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DonateProvider>
        <Box maxW="5xl" margin="auto">
          <Heading />
          <DonationFormHeading />
          <Box marginY="5rem" />
          <LatestDonators />
        </Box>
      </DonateProvider>
    </ClientLayout>
  )
}

export default Donate
