import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import events from '~/components/client/events/calendar/dummy'
import Calendar from '~/components/client/events/calendar/index'
import Heading from '~/components/client/events/heading/Heading'
import ClientLayout from '~/layouts/Client'
const Events = () => {
  return (
    <ClientLayout>
      <Head>
        <title>Eventos - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading />
        <Calendar events={events} />
      </Box>
    </ClientLayout>
  )
}

export default Events
