import Head from 'next/head'
import AboutUs from '~/components/client/landing/about-us'
import AditionalInformation from '~/components/client/landing/aditional-information'
import Hero from '~/components/client/landing/hero'
import SupportUs from '~/components/client/landing/support-us'
import ClientLayout from '~/layouts/Client'

const Home = () => {
  return (
    <ClientLayout>
      <div>
        <Head>
          <title>Gotas de Luz - Iluminando momentos para generar vida</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <AboutUs />
        <AditionalInformation />
        <SupportUs />
      </div>
    </ClientLayout>
  )
}

export default Home
