import { Text } from '@chakra-ui/react'
import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>test</Text>
    </div>
  )
}

export default Home
