import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import NewsList from '~/components/client/news/card/List'
import Heading from '~/components/client/news/heading/Heading'
import ClientLayout from '~/layouts/Client'
import { NewsI } from '~/lib/models/news'
import prisma from '~/lib/prisma'
interface Props {
  news: NewsI[]
}
const NewsPage = ({ news }: Props) => {
  return (
    <ClientLayout>
      <Head>
        <title>Novedades - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading />
        <NewsList news={news} />
      </Box>
    </ClientLayout>
  )
}

export async function getStaticProps() {
  const news = await prisma.news.findMany()
  return {
    props: { news },
  }
}

export default NewsPage
