import Head from 'next/head'
import { NewsFeed } from '~/components/client/news/Feed'
import ClientLayout from '~/layouts/Client'
import { NewsI } from '~/lib/models/news'
interface Props {
  news: NewsI[]
}
const NewsPage = ({ news }: Props) => {
  return (
    <ClientLayout>
      <Head>
        <title>Novedades - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewsFeed />
    </ClientLayout>
  )
}

export default NewsPage
