import Head from 'next/head'
import { VolunteersLayout } from '~/components/client/volunteers/Layout'
import withAnimation from '~/hoc/withAnimation'
import ClientLayout from '~/layouts/Client'

const Volunteers = () => {
  return (
    <ClientLayout>
      <Head>
        <title>Voluntariado - Gotas de Luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VolunteersLayout />
    </ClientLayout>
  )
}

export default withAnimation(Volunteers)
